#! /bin/bash

set -e

cd "$(dirname $0)"

problem_name="$1"
[[ -d $problem_name ]] || mkdir $problem_name
cd $problem_name

if [[ ! -s solution ]]; then
  solution_template='#! /usr/bin/env awk -f

# DISCLAIMER - If you are interested in the Rosalind Project, please solve
# this problem on your own before reading my solution.

'

  echo "$solution_template" > solution
  chmod +x solution
fi

if [[ ! -s test ]]; then
  test_template='#! /bin/bash

set -e

cd "$(dirname $0)"
source "../lib/test_helper.sh"

'
  echo "$test_template" > test
  chmod +x test
fi
