#! /usr/bin/env awk -f

# DISCLAIMER - If you are interested in the Rosalind Project, please solve
# this problem on your own before reading my solution.

BEGIN {
  RS = ""
  FS = "\n"
}

# Calculates the Hamming distance between a pair of DNA sequences.
# http://rosalind.info/problems/hamm/
function hamming(seq_a, seq_b,   mutations, len, char_a, char_b) {
  len = length(seq_a)
  mutations = 0

  for(i = 1; i <= len; i++) {
    char_a = substr(seq_a, i, 1)
    char_b = substr(seq_b, i, 1)
    if(char_a != char_b) { mutations++ }
  }

  return mutations
}

{ print hamming($1, $2) }
