#! /usr/bin/env awk -f

BEGIN {
  # Phenome probabilities:
  e[0,0] = 1.00; e[0,1] = 1.00; e[0,2] = 1.00
  e[1,0] = 1.00; e[1,1] = 0.75; e[1,2] = 0.50
  e[2,0] = 1.00; e[2,1] = 0.50; e[2,2] = 0.00
}

function prob(a,b, pop,total,   sa, sb) {
  sa = pop[a]
  sb = (a == b) ? pop[b] - 1 : pop[b]
  return (sa / total) * sb / (total - 1) * e[a,b]
}

# 0 k = Dominant homozygous population segment
# 1 m = Heterozygous population segment
# 2 n = Recessive homozygous population segment
{
  pop[0] = int($1); pop[1] = int($2); pop[2] = int($3)
  total = int($1) + int($2) + int($3)

  for(i = 0; i < 3; i++) {
    for(j = 0; j < 3; j++) {
      pi += prob(i,j, pop, total)
    }
  }

  printf("%0.5f", pi)
}
