#! /usr/bin/env awk -f

BEGIN {
  # Phenome probabilities:
  e_kk = 1.00; e_mk = 1.00; e_nk = 1.00
  e_km = 1.00; e_mm = 0.75; e_nm = 0.50
  e_kn = 1.00; e_mn = 0.50; e_nn = 0.00
}

# k = Dominant homozygous population segment
# m = Heterozygous population segment
# n = Recessive homozygous population segment
{
  k = int($1); m = int($2); n = int($3)
  t = k + m + n

  # I can use global variables to make a function here, but that feels somehow
  # worse than this jumbled mess. Not sure how to gereralize this.
  p["kk"] = (k/t) * (k-1)/(t-1) * e_kk
  p["km"] = (k/t) * (m)/(t-1) * e_km
  p["kn"] = (k/t) * (n)/(t-1) * e_kn

  p["mk"] = (m/t) * (k)/(t-1) * e_mk
  p["mm"] = (m/t) * (m-1)/(t-1) * e_mm
  p["mn"] = (m/t) * (n)/(t-1) * e_mn

  p["nk"] = (n/t) * (k)/(t-1) * e_nk
  p["nm"] = (n/t) * (m)/(t-1) * e_nm
  p["nn"] = (n/t) * (n-1)/(t-1) * e_nn

  for(pair in p) { pi += p[pair] }
  printf("%0.5f", pi)
}

