#! /bin/bash

set -e

script_dir=$(dirname $0)
source "${script_dir}/../lib/test_helper.sh"

cd $script_dir

example="GATGGAACTTGACTACGTAAATT"
expected="GAUGGAACUUGACUACGUAAAUU"

assert_eql "$(solve $example)" "$expected"
