#! /usr/bin/env awk -f

# DISCLAIMER - If you are interested in the Rosalind Project, please solve
# this problem on your own before reading my solution.
BEGIN {
  # Build RNA Codon Table
  while((getline < "./rna_codons") > 0) {
    for(i = 1; i < NF; i += 2) { codons[$i] = $(i + 1) }
  }
}

{
  seq_len = length($0)
  for(i = 1; i <= seq_len; i += 3) {
    sub_seq = substr($0, i, 3)
    codon = codons[sub_seq]
    if(codon == "Stop") break
    printf codon
  }
}
