#! /bin/bash

set -e

cd "$(dirname $0)"
source "../lib/test_helper.sh"

example="AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
expected="20 12 17 21"

assert_eql "$(solve $example)" "$expected"
