#! /usr/bin/env awk -f

# DISCLAIMER - If you are interested in the Rosalind Project, please solve
# this problem on your own before reading my solution.

{
  n = int($1)
  k = int($2)

  f[1] = 1
  f[2] = 1

  for(i = 3; i <= n; i++) {
    f[i] = f[i - 1] + f[i - 2] * k
  }

  print f[n]
}
