#! /bin/bash

set -e

cd "$(dirname $0)"
source "../lib/test_helper.sh"

assert_eql "$(solve "1 3")" "1"
assert_eql "$(solve "2 3")" "1"
assert_eql "$(solve "3 3")" "4"
assert_eql "$(solve "4 3")" "7"
assert_eql "$(solve "5 3")" "19"
